
/* eslint-disable react/react-in-jsx-scope */

import type {Metadata} from 'next';
import localFont from 'next/font/local';
import './globals.scss';
import styles from '@/app/global.module.scss';
import {Header} from '@/components/Header';
const studioPro = localFont({
	src: [
		{
			path: '../assets/fonts/HeroBold700.otf',
			weight: '600',
			style: 'normal',
		},
	],
	variable: '--font-studio-pro',
});

export const metadata: Metadata = {
	title: 'Next | Nome page',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={studioPro.variable}>
				<Header/>
				<main>
					{children}
				</main>
			</body>
		</html>
	);
}
